# Generated by Django 3.1 on 2021-05-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.IntegerField(choices=[(1, 'Voice Therapy'), (2, 'Speech Therapy'), (3, 'Speech Therapy Classes'), (4, 'Speech Therapy Benifits')])),
                ('patient_name', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('appointment_id', models.CharField(max_length=50)),
            ],
        ),
    ]
